services:
  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./docker-files/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./docker-files/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:18.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=deposit-collector

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    volumes:
      - ./docker-files/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      rabbitmq:
        condition: service_healthy

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "10000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./docker-files/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker-files/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

  hardhat:
    build:
      context: .
      dockerfile: hardhat/Dockerfile
    init: true
    command: npm run start
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 5

  bitcoind:
    image: bitcoin/bitcoin:28.4-alpine
    entrypoint: ["/bin/sh", "/start.sh"]
    volumes:
      - ./docker-files/bitcoin-node/start.sh:/start.sh:ro
      - ./docker-files/bitcoin-node/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro
    environment:
      - MINER_ADDRESS=bcrt1qdm9wyf60upmuyq87w3s75r33gkucza0tqfgg6a
    ports:
      - "18443:18443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18443"]
      interval: 1s
      timeout: 10s
      retries: 5
  electrumx:
    image: lukechilds/electrumx
    ports:
      - "50001:50001"
      - "18000:18000"
    environment:
      - DAEMON_URL=http://admin:admin@bitcoind:18443/
      - COIN=Bitcoin
      - NET=regtest
      - SERVICES=tcp://0.0.0.0:50001,rpc://0.0.0.0:18000
    depends_on:
      - bitcoind
